- name: update certs
  command:
    cmd: update-ca-certificates
#    become: yes

- name: restart time client
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted

- name: restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
